### ISSUE TITLE
How to deal with status array when unloaded from tracker memory?

### ISSUE THREAD

**Issue by geilsonrm** [aerosales10/nest-gps-server#6]
Hello!

Some trackers when they go to unload the memory, they send a package with several statuses (zip) instead of just one (string).

I'm currently experiencing this with Suntech's ST300HD tracker.

Is there an easy way to handle this at NestGpsServer?

**Comment by aerosales10** [comment]
Hi @geilsonrm, Can you please share an example of the data that you are receiving? But a hint could be implementing an adapter with a statuses queue and processing them later.

**Comment by geilsonrm** [comment]
@aerosales10 

Thanks for the quick response.

Here is an example of when a status arrives and when a list arrives:


Common status:
`[ 'SA200STT;739035;H-1095;20200923;17:34:15;8b347;-20.251733;-040.272192;000.937;000.00;8;1;252400;12.32;100000;2;1757;007435;4.1;0;0;00000000000000;0' ]`

Status list:
```
[ 'SA200STT;739035;H-1095;20200923;17:36:45;8b347;-20.251770;-040.272130;001.667;000.00;8;1;252470;12.32;100000;2;1762;007438;4.1;0;0;00000000000000;0',
  'SA200STT;739035;H-1095;20200923;17:36:15;8b347;-20.251971;-040.271974;000.131;000.00;8;1;252470;12.32;100000;2;1761;007437;4.1;0;0;00000000000000;0',
  'SA200STT;739035;H-1095;20200923;17:35:45;8b347;-20.251831;-040.272073;001.535;000.00;7;1;252400;12.32;100000;2;1760;007437;4.1;0;0;00000000000000;0',
  'SA200STT;739035;H-1095;20200923;17:35:15;8b347;-20.251794;-040.272137;000.089;000.00;7;1;252400;12.32;100000;2;1759;007436;4.1;0;0;00000000000000;0',
  'SA200STT;739035;H-1095;20200923;17:34:45;8b347;-20.251762;-040.272164;000.893;000.00;8;1;252400;12.29;100000;2;1758;007436;4.1;0;0;00000000000000;0' ]
```

**Comment by geilsonrm** [comment]
@aerosales10 I forgot to mention that I used data.split ('\ r') So common status was in brackets too.

**Comment by aerosales10** [comment]
Hi @geilsonrm,
I can see the issue now. The current code does not allows you to have multiple incoming statuses, I will fix that and I will notify you when it's done.

**Comment by aerosales10** [comment]
Hi @geilsonrm,
The lib now supports parsing multiple data in one stream. The adapter in the parse_data method can return a Promise<GpsMessagePartsInterface> for a single message parsed or Promise<GpsMessagePartsInterface[]> for multple messages parsed.

Simple Echo with multiple responses:
```typescript
async parse_data(data: string | Buffer): Promise<GpsMessagePartsInterface[]> {
        let str_data = data.toString().trim();
        let response = {
            action: GPS_MESSAGE_ACTION.PING,
            cmd: "Echo",
            data: str_data,
            device_id: `${this.device.ip}-${this.device.port}`
        };

        if (str_data == "login")
            response.action = GPS_MESSAGE_ACTION.LOGIN_REQUEST;
        // After you parse the responses you can return the array with the parsed data
        // Everything else maintains the same
        return [response, response];
    }

**Comment by geilsonrm** [comment]
@aerosales10 

Worked perfectly!!!

Thank you very much for resolving it quickly!
