### ISSUE TITLE
How to disable logger?

### ISSUE THREAD

**Issue by geilsonrm** [aerosales10/nest-gps-server#7]
Hi! I am testing the application on AWS, but I am having a high volume of logger, since each status of the tracker is shown on the console.

How can I disable it?

Below is an example of a log that I need not to appear. Thanks!!!

```
[Nest] 15920   - 2020-12-05 11:23:37 AM   808080 is trying to PING but isn't logged. Action wasn't executed. +0ms
[Nest] 15920   - 2020-12-05 11:23:37 AM   Device 808080 has been authorized. +4ms
[Nest] 15920   - 2020-12-05 11:23:37 AM   [808080]Receiving raw data: SA200STT;808080;131;20201205;14:23:36;8b326;-20.252463;-040.271104;000.018;000.00;9;1;1218320;12.07;100110;2;0556 +8ms
[Nest] 15920   - 2020-12-05 11:23:39 AM   [808080]Position received ( -20.252463, -40.271104 ) Sat Dec 05 2020 11:23:36 GMT-0300 (GMT-03:00) +1435ms
[Nest] 15920   - 2020-12-05 11:23:39 AM   Incomming connection from 189.96.41.114:6180 +705ms
 +19ms 15920   - 2020-12-05 11:23:39 AM   [undefined]Receiving raw data: SA200ALV;739035
[Nest] 15920   - 2020-12-05 11:24:12 AM   Device 189.92.41.114:6180 disconnected. +32324ms
```

**Comment by geilsonrm** [comment]
Hi! Any news on this?

**Comment by aerosales10** [comment]
Hi @geilsonrm. I'm sorry I've been busy. This weekend I will take a look. You can pass your custom logger.

**Comment by aerosales10** [comment]
You can pass to the module this options:
```typescript
// This are all the valid options
export interface GpsServerOptionsInterface {
    port: number;
    bind?: string;
    adapter?: Type<GpsAdapterInterface>;
    logger?: Type<LoggerService>;
    device_factory?: Type<DeviceAbstractFactory>;
    imports?: Array<Type<any> | DynamicModule | Promise<DynamicModule> | ForwardReference>,
    providers?: Provider[];
    useUDP?: boolean;
    useTCP?: boolean;
};

import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { GpsServerModule } from '@aerosales10/nest-gps-server';
@Module({
  imports: [GpsServerModule.forRoot({
    port: 8086,
    logger: MyCustomLogger
  })],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

**Comment by geilsonrm** [comment]
Thanks for the feedback!

I created to test the logger below:

```
import { Injectable, LoggerService } from '@nestjs/common';

@Injectable()
export class CustomLogger implements LoggerService {
  log(message: string) {
    console.log(message);
  }

  error(message: string, trace: string) {
    console.log(message);
  }

  warn(message: string) {
    console.log(message);
  }

  debug(message: string) {
    console.log(message);
  }

  verbose(message: string) {
    console.log(message);
  }
}
```

I am calling as mentioned:
```
const gpsServerOptions: GpsServerOptionsInterface = {
  logger: CustomLogger,
  port: 5009,
  (...)
}

@Module({
  GpsServerModule.forRoot(gpsServerOptions),
  (...)
})
```

But I have the following error:

```
(node:20256) UnhandledPromiseRejectionWarning: TypeError: this.logger.debug is not a function
    at GpsTCPServerService.onApplicationBootstrap (C:\geilson\gr-code\gr-base-backend\node_modules\@aerosales10\nest-gps-server\dist\src\gps-tcp-server.service.js:63:21)
    at MapIterator.iterare_1.iterate.filter.filter.map [as iteratee] (C:\geilson\gr-code\gr-base-backend\node_modules\@nestjs\core\hooks\on-app-bootstrap.hook.js:22:43)
    at MapIterator.next (C:\geilson\gr-code\gr-base-backend\node_modules\iterare\lib\map.js:13:39)
    at IteratorWithOperators.next (C:\geilson\gr-code\gr-base-backend\node_modules\iterare\lib\iterate.js:21:28)
    at Function.from (<anonymous>)
    at IteratorWithOperators.toArray (C:\geilson\gr-code\gr-base-backend\node_modules\iterare\lib\iterate.js:180:22)
    at callOperator (C:\geilson\gr-code\gr-base-backend\node_modules\@nestjs\core\hooks\on-app-bootstrap.hook.js:23:10)
    at Object.callModuleBootstrapHook (C:\geilson\gr-code\gr-base-backend\node_modules\@nestjs\core\hooks\on-app-bootstrap.hook.js:43:23)
    at NestApplication.callBootstrapHook (C:\geilson\gr-code\gr-base-backend\node_modules\@nestjs\core\nest-application-context.js:182:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:20256) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)(node:20256) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:20256) UnhandledPromiseRejectionWarning: TypeError: self.logger.debug is not a function
    at GpsTCPServerService.connection_handler (C:\geilson\gr-code\gr-base-backend\node_modules\@aerosales10\nest-gps-server\dist\src\gps-tcp-server.service.js:31:21)
    at Server.emit (events.js:198:13)
    at TCP.onconnection (net.js:1520:8)
(node:20256) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

Please, can you help me? Thank you!

**Comment by aerosales10** [comment]
Hi @geilsonrm , It's seems that is expecting an instance of the logger:
```typescript
options.providers.push({ provide: 'GPS_LOGGER', useValue: (options.logger) ? options.logger : Logger });
```
Can you please try to pass an Instance?

**Comment by geilsonrm** [comment]
Would it be this?

```
import { Injectable, LoggerService } from '@nestjs/common';

@Injectable()
export class CustomLogger implements LoggerService {
  log(message: string) {
    console.log(message);
  }
  error(message: string, trace: string) {
    console.log(message);
  }
  warn(message: string) {
    console.log(message);
  }
  debug(message: string) {
    console.log(message);
  }
  verbose(message: string) {
    console.log(message);
  }
}


const gpsServerOptions: GpsServerOptionsInterface = {
   logger: CustomLogger,
   port: 5009,
   (...)
}

gpsServerOptions.providers.push ({
   provide: 'GPS_LOGGER',
   useValue: (gpsServerOptions.logger)? gpsServerOptions.logger: CustomLogger,
});

@Module ({
   GpsServerModule.forRoot (gpsServerOptions),
   (...)
})
```

He continued to display the same error message reported earlier.

**Comment by aerosales10** [comment]
@geilsonrm It should be an instance object of the class that you created. But this week end I will try to make the logger injectable.

**Comment by geilsonrm** [comment]
@aerosales10 If you can work on it it will be great.

I'm trying to use the application on AWS, but the excess of logs is driving up the cost of CloudWatch.

I disabled the logs on AWS, but without it I can't see the possible problem I'm having.

Thank you!

**Comment by aerosales10** [comment]
> Thanks for the feedback!
> 
> I created to test the logger below:
> 
> ```
> import { Injectable, LoggerService } from '@nestjs/common';
> 
> @Injectable()
> export class CustomLogger implements LoggerService {
>   log(message: string) {
>     console.log(message);
>   }
> 
>   error(message: string, trace: string) {
>     console.log(message);
>   }
> 
>   warn(message: string) {
>     console.log(message);
>   }
> 
>   debug(message: string) {
>     console.log(message);
>   }
> 
>   verbose(message: string) {
>     console.log(message);
>   }
> }
> ```
> 
> I am calling as mentioned:
> 
> ```
> const gpsServerOptions: GpsServerOptionsInterface = {
>   logger: CustomLogger,
>   port: 5009,
>   (...)
> }
> 
> @Module({
>   GpsServerModule.forRoot(gpsServerOptions),
>   (...)
> })
> ```
> 
> But I have the following error:
> 
> ```
> (node:20256) UnhandledPromiseRejectionWarning: TypeError: this.logger.debug is not a function
>     at GpsTCPServerService.onApplicationBootstrap (C:\geilson\gr-code\gr-base-backend\node_modules\@aerosales10\nest-gps-server\dist\src\gps-tcp-server.service.js:63:21)
>     at MapIterator.iterare_1.iterate.filter.filter.map [as iteratee] (C:\geilson\gr-code\gr-base-backend\node_modules\@nestjs\core\hooks\on-app-bootstrap.hook.js:22:43)
>     at MapIterator.next (C:\geilson\gr-code\gr-base-backend\node_modules\iterare\lib\map.js:13:39)
>     at IteratorWithOperators.next (C:\geilson\gr-code\gr-base-backend\node_modules\iterare\lib\iterate.js:21:28)
>     at Function.from (<anonymous>)
>     at IteratorWithOperators.toArray (C:\geilson\gr-code\gr-base-backend\node_modules\iterare\lib\iterate.js:180:22)
>     at callOperator (C:\geilson\gr-code\gr-base-backend\node_modules\@nestjs\core\hooks\on-app-bootstrap.hook.js:23:10)
>     at Object.callModuleBootstrapHook (C:\geilson\gr-code\gr-base-backend\node_modules\@nestjs\core\hooks\on-app-bootstrap.hook.js:43:23)
>     at NestApplication.callBootstrapHook (C:\geilson\gr-code\gr-base-backend\node_modules\@nestjs\core\nest-application-context.js:182:27)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> (node:20256) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)(node:20256) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> (node:20256) UnhandledPromiseRejectionWarning: TypeError: self.logger.debug is not a function
>     at GpsTCPServerService.connection_handler (C:\geilson\gr-code\gr-base-backend\node_modules\@aerosales10\nest-gps-server\dist\src\gps-tcp-server.service.js:31:21)
>     at Server.emit (events.js:198:13)
>     at TCP.onconnection (net.js:1520:8)
> (node:20256) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
> ```
> 
> Please, can you help me? Thank you!

@geilsonrm  Now you can pass your custom logger like this.
